server:
  port: 8090
spring:
  jpa:
#  是否自动创建ddl语句
    generate-ddl: true
    #  是否打印sql语句
    show-sql: true
    #  hibernate是否自动创建ddl语句
    hibernate:
      ddl-auto: create


  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: zhangjc
    password: zhangjc
    initialize: true
#日志配置
logging:
  level:
    root: info
#    打印SQL语句
    org.hibernate: info
    org.hibernate.type.description.sql.BasicBinder: trace
    org.hibernate.type.description.sql.BaseExtractor: trace
    com.zhang: debug



